server:
  port: 8080

spring:
  profiles:
    active: production

  datasource:
    url: jdbc:mysql://localhost:3306/oms?autoReconnect=true&useSSL=true
    username: root
    password: root

  jpa:
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  main:
    banner-mode: "off"

  jackson:
    serialization:
      write_dates_as_timestamps: false